# Generated by Django 3.2.5 on 2021-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='last_change',
            field=models.DateTimeField(null=True),
        ),
    ]
