# Generated by Django 3.2.5 on 2021-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_shoppinglist_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='owner',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='display_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
