# Generated by Django 3.2.5 on 2021-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_auto_20210711_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
