# Generated by Django 3.2.5 on 2021-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0005_remove_shoppinglist_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
