# Generated by Django 3.2.5 on 2021-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0006_listentry_removed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='removed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
