# Generated by Django 3.2.5 on 2021-07-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0008_auto_20210711_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='owner',
        ),
    ]
