# Generated by Django 3.2.5 on 2021-07-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0009_remove_shoppinglist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='owner',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
